spring:
  profiles:
    active:
      - dev

---

spring:
  profiles: dev
  application:
    name: cloud-config-client-dev

---

spring:
  profiles: test
  application:
    name: cloud-config-client-test
