spring:
  profiles:
    active:
      - dev

---

server:
  port: 8881
spring:
  profiles: dev
  application:
    name: cloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka/

---

server:
  port: 8882
spring:
  profiles: test
  application:
    name: cloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka02:7002/eureka/
